version: "3"
services:
  app:
    image: "postgres-spring:latest"
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ ## Enter username after the '/'
      - SPRING_DATASOURCE_USERNAME= ## Enter a username
      - SPRING_DATASOURCE_PASSWORD= ## Enter a password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: "postgres:13.1-alpine"
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER= ## Enter a username
      - POSTGRES_PASSWORD= ## Enter a password
  postgres:
    image: postgres:9.6-alpine
    restart: always
    hostname: kong-database
    container_name: kong-database
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kong"
    ports:
      - "5433:5433"

  ## Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  ## Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER= ## Enter a username
      - GF_SECURITY_ADMIN_PASSWORD= ## Enter a password

  kong-bootstrap:
    image: kong/kong-gateway:latest
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
    command: "kong migrations bootstrap"
    restart: "on-failure"
  kong:
    image: kong/kong-gateway:latest
    restart: always
    hostname: kong
    container_name: kong
    depends_on:
      - kong-bootstrap
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8433:8433"
      - "8001:8001"
      - "8444:8444"
networks:
  default:
    name: kong-net
