{
 "title": "Basic-API-Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "4xx and 5xx status code across all URIs",
   "type": "timeseries",
   "description": "Count of 4xx and 5xx status codes across all endpoints in API",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status!~\"204|200|201\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "2xx status code across all URIs",
   "type": "timeseries",
   "description": "Count of 2xx status codes across ",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=~\"204|200|201\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}