scrape_configs:
  - job_name: "Microservice Monitor"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:8080"]
        labels:
          application: "Microservice Monitor"

  - job_name: "Kong Monitor"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:8001"]
        labels:
          application: "Kong Monitor"
